[pytest]
norecursedirs = .* build dist CVS _darcs {arch} *.egg venv node_modules .DS_Store
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -p no:warnings --ignore=.DS_Store
asyncio_mode = auto
