"""Create tables with partner created_at

Revision ID: 0ef95c8f787d
Revises: ee26570e6422
Create Date: 2026-02-07 19:15:05.809890

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0ef95c8f787d'
down_revision: Union[str, Sequence[str], None] = 'ee26570e6422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('partner', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('partner', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('partner', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner', 'created_at')
    op.drop_column('partner', 'photo_url')
    op.drop_column('partner', 'last_name')
    op.drop_table('earning')
    # ### end Alembic commands ###
