"""add_unlocked_stages_to_partner

Revision ID: 101a3eb4c65e
Revises: a2ddc7582b0e
Create Date: 2026-02-24 03:21:52.653766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '101a3eb4c65e'
down_revision: Union[str, Sequence[str], None] = 'a2ddc7582b0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broadcast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_partner_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked_stages', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='[]'))

    with op.batch_alter_table('socialpostmetric', schema=None) as batch_op:
        batch_op.alter_column('reactions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('shares',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialpostmetric', schema=None) as batch_op:
        batch_op.alter_column('shares',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('reactions',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_column('unlocked_stages')

    with op.batch_alter_table('broadcast', schema=None) as batch_op:
        batch_op.drop_column('last_partner_id')

    # ### end Alembic commands ###
