"""Add SystemSetting table

Revision ID: 137ba628be77
Revises: head_index_fix
Create Date: 2026-02-10 03:14:59.572387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '137ba628be77'
down_revision: Union[str, Sequence[str], None] = 'head_index_fix'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'systemsetting' not in tables:
        op.create_table('systemsetting',
            sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
            sa.Column('updated_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('key')
        )
        with op.batch_alter_table('systemsetting', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_systemsetting_updated_at'), ['updated_at'], unique=False)
    else:
        print("✅ Table 'systemsetting' already exists, skipping creation.")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('systemsetting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_systemsetting_updated_at'))

    op.drop_table('systemsetting')
    # ### end Alembic commands ###
