"""add broadcast table

Revision ID: 1c6347c4fd08
Revises: fef308b386d4
Create Date: 2026-02-20 19:51:40.571393

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c6347c4fd08'
down_revision: str | Sequence[str] | None = 'fef308b386d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audience_type', sa.Enum('ALL', 'PRO_ONLY', 'FREE_ONLY', 'LEVEL_1', 'INACTIVE_7D', name='audiencefilter', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENDING', 'COMPLETED', 'PAUSED', 'CANCELLED', 'FAILED', name='broadcaststatus', native_enum=False), nullable=True),
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcast', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcast_status'), ['status'], unique=False)

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_earning_reference_id', ['reference_id'])

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_partner_task', ['partner_id', 'task_id'])

    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_partner_xp_ref', ['partner_id', 'type', 'reference_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_xp_ref', type_='unique')

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_task', type_='unique')

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_constraint('uq_earning_reference_id', type_='unique')

    with op.batch_alter_table('broadcast', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcast_status'))
        batch_op.drop_index(batch_op.f('ix_broadcast_admin_id'))

    op.drop_table('broadcast')
    # ### end Alembic commands ###
