"""add is_test to partner

Revision ID: 3577c7444ec3
Revises: 20260301_audit_scaling_v1
Create Date: 2026-03-17 09:54:54.244072

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3577c7444ec3'
down_revision: str | Sequence[str] | None = '20260301_audit_scaling_v1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_audit_type_created'))

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_test', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_index(batch_op.f('ix_partner_is_test'), ['is_test'], unique=False)

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_tx_status_created'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tx_status_created'), ['status', 'created_at'], unique=False)

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_is_test'))
        batch_op.drop_column('is_test')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_audit_type_created'), ['action_type', 'created_at'], unique=False)

    # ### end Alembic commands ###
