"""Add KnowledgeBaseItem

Revision ID: 3927c88c1bac
Revises: bd17f56f5717
Create Date: 2026-02-13 17:04:42.373888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3927c88c1bac'
down_revision: Union[str, Sequence[str], None] = 'bd17f56f5717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'knowledgebaseitem' not in tables:
        op.create_table('knowledgebaseitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('knowledgebaseitem', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_knowledgebaseitem_category'), ['category'], unique=False)
            batch_op.create_index(batch_op.f('ix_knowledgebaseitem_key'), ['key'], unique=False)
    else:
        print("✅ Table 'knowledgebaseitem' already exists, skipping creation.")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledgebaseitem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledgebaseitem_key'))
        batch_op.drop_index(batch_op.f('ix_knowledgebaseitem_category'))

    op.drop_table('knowledgebaseitem')
    # ### end Alembic commands ###
