"""upgrade_audit_log_schema

Revision ID: 42aa9d7756cd
Revises: e413c716e037
Create Date: 2026-02-20 14:22:51.715490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42aa9d7756cd'
down_revision: Union[str, Sequence[str], None] = 'e413c716e037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_id', sa.Integer(), nullable=True))
        
        # Manually create ENUM type for PostgreSQL
        action_type_enum = sa.Enum('SYSTEM', 'UPGRADE', 'PAYMENT', 'COMMISSION', 'PENALTY', 'MISC', name='actiontype')
        action_type_enum.create(op.get_bind(), checkfirst=True)
        
        batch_op.add_column(sa.Column('action_type', action_type_enum, server_default='MISC', nullable=False))
        batch_op.add_column(sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_audit_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_partner_id'), ['partner_id'], unique=False)
        batch_op.create_foreign_key(None, 'partner', ['partner_id'], ['id'])

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_earning_reference_id'))
        batch_op.create_index('idx_earning_partner_created', ['partner_id', 'created_at'], unique=False)
        batch_op.create_index('idx_earning_partner_type_created', ['partner_id', 'type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_reference_id'), ['reference_id'], unique=False)

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.create_index('idx_partner_ispro_expires', ['is_pro', 'pro_expires_at'], unique=False, postgresql_where=sa.text('is_pro = true'))
        batch_op.create_index('idx_partner_referrer_created', ['referrer_id', 'created_at'], unique=False)
        batch_op.drop_column('completed_tasks')

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        pass # Skipped due to old data overlaps 

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.create_index('idx_tx_partner_status_created', ['partner_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnertransaction_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnertransaction_status'), ['status'], unique=False)

    with op.batch_alter_table('socialpost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_socialpost_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_socialpost_generation_id'), ['generation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_socialpost_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('viralgeneration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viralgeneration_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_viralgeneration_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.create_index('idx_xp_partner_created', ['partner_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_xp_ref', type_='unique')
        batch_op.drop_index('idx_xp_partner_created')

    with op.batch_alter_table('viralgeneration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viralgeneration_partner_id'))
        batch_op.drop_index(batch_op.f('ix_viralgeneration_created_at'))

    with op.batch_alter_table('socialpost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_socialpost_partner_id'))
        batch_op.drop_index(batch_op.f('ix_socialpost_generation_id'))
        batch_op.drop_index(batch_op.f('ix_socialpost_created_at'))

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partnertransaction_status'))
        batch_op.drop_index(batch_op.f('ix_partnertransaction_currency'))
        batch_op.drop_index('idx_tx_partner_status_created')

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_task', type_='unique')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_tasks', sa.VARCHAR(), server_default=sa.text("'[]'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_partner_referrer_created')
        batch_op.drop_index('idx_partner_ispro_expires', postgresql_where=sa.text('is_pro = true'))

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_constraint('uq_earning_reference_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_earning_reference_id'))
        batch_op.drop_index(batch_op.f('ix_earning_level'))
        batch_op.drop_index(batch_op.f('ix_earning_currency'))
        batch_op.drop_index('idx_earning_partner_type_created')
        batch_op.drop_index('idx_earning_partner_created')
        batch_op.create_index(batch_op.f('idx_earning_reference_id'), ['reference_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_audit_log_partner_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action_type'))
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('entity_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('action_type')
        batch_op.drop_column('partner_id')

    # ### end Alembic commands ###
