"""add channel_name to socialpost

Revision ID: 596594295c49
Revises: 1c6347c4fd08
Create Date: 2026-02-21 13:31:11.981859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '596594295c49'
down_revision: Union[str, Sequence[str], None] = '1c6347c4fd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialpost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('socialpost', schema=None) as batch_op:
        batch_op.drop_column('channel_name')

    # ### end Alembic commands ###
