"""add partnertask association table

Revision ID: 73a319c82804
Revises: 7c69a3e9226a
Create Date: 2026-02-08 23:40:26.670539

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73a319c82804'
down_revision: Union[str, Sequence[str], None] = '7c69a3e9226a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partnertask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('reward_xp', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partnertask_partner_id'), 'partnertask', ['partner_id'], unique=False)
    op.create_index(op.f('ix_partnertask_task_id'), 'partnertask', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partnertask_task_id'), table_name='partnertask')
    op.drop_index(op.f('ix_partnertask_partner_id'), table_name='partnertask')
    op.drop_table('partnertask')
    # ### end Alembic commands ###
