"""add updated_at and index on path

Revision ID: 7c69a3e9226a
Revises: a1b2c3d4e5f6
Create Date: 2026-02-08 23:38:51.873663

"""
from datetime import datetime
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c69a3e9226a'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_earning_created_at'), 'earning', ['created_at'], unique=False)
    op.create_index(op.f('ix_earning_partner_id'), 'earning', ['partner_id'], unique=False)

    # SQLite doesn't support sa.func.now() as a default for new columns
    sa.func.now()
    if op.get_context().dialect.name == 'sqlite':
        datetime(2026, 1, 1)

    op.add_column('partner', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("'2026-01-01 00:00:00'") if op.get_context().dialect.name == 'sqlite' else sa.func.now()))
    op.alter_column('partner', 'language_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'en'::character varying"))
    op.alter_column('partner', 'completed_tasks',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'[]'::character varying"))
    op.drop_index(op.f('idx_partner_path'), table_name='partner')
    op.drop_constraint(op.f('partner_referral_code_key'), 'partner', type_='unique')
    op.create_index(op.f('ix_partner_created_at'), 'partner', ['created_at'], unique=False)
    op.create_index(op.f('ix_partner_path'), 'partner', ['path'], unique=False)
    op.create_index(op.f('ix_partner_referral_code'), 'partner', ['referral_code'], unique=True)
    op.create_index(op.f('ix_partner_referrer_id'), 'partner', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_partner_updated_at'), 'partner', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_updated_at'), table_name='partner')
    op.drop_index(op.f('ix_partner_referrer_id'), table_name='partner')
    op.drop_index(op.f('ix_partner_referral_code'), table_name='partner')
    op.drop_index(op.f('ix_partner_path'), table_name='partner')
    op.drop_index(op.f('ix_partner_created_at'), table_name='partner')
    op.create_unique_constraint(op.f('partner_referral_code_key'), 'partner', ['referral_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_partner_path'), 'partner', ['path'], unique=False)
    op.alter_column('partner', 'completed_tasks',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'[]'::character varying"))
    op.alter_column('partner', 'language_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'en'::character varying"))
    op.drop_column('partner', 'updated_at')
    op.drop_index(op.f('ix_earning_partner_id'), table_name='earning')
    op.drop_index(op.f('ix_earning_created_at'), table_name='earning')
    # ### end Alembic commands ###
