"""make_audit_log_created_at_non_nullable

Revision ID: a2ddc7582b0e
Revises: 39f62e173494
Create Date: 2026-02-21 19:05:21.757931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ddc7582b0e'
down_revision: Union[str, Sequence[str], None] = '39f62e173494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'created_at',
               existing_type=sa.DateTime(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'created_at',
               existing_type=sa.DateTime(),
               nullable=True)
    # ### end Alembic commands ###
