"""Add audit_log table

Revision ID: bd17f56f5717
Revises: 05d9390824e8
Create Date: 2026-02-13 16:50:48.587215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd17f56f5717'
down_revision: Union[str, Sequence[str], None] = '05d9390824e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partnerbloglike', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partnerbloglike_partner_id'))
        batch_op.drop_index(batch_op.f('ix_partnerbloglike_post_slug'))

    op.drop_table('partnerbloglike')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_partner_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_tx_hash'))

    op.drop_table('transaction')
    with op.batch_alter_table('blogpostengagement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogpostengagement_post_slug'))

    op.drop_table('blogpostengagement')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_audit_log_admin_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_category_success'))
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_partner_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_related_partner_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_request_id'))
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_entity_type'), ['entity_type'], unique=False)
        batch_op.drop_constraint(batch_op.f('audit_log_partner_id_fkey'), type_='foreignkey')
        batch_op.drop_column('partner_id')
        batch_op.drop_column('metadata')
        batch_op.drop_column('event_category')
        batch_op.drop_column('request_id')
        batch_op.drop_column('success')
        batch_op.drop_column('currency')
        batch_op.drop_column('amount')
        batch_op.drop_column('event_type')
        batch_op.drop_column('related_partner_id')
        batch_op.drop_column('error_message')
        batch_op.drop_column('balance_after')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('balance_before')
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'COMMISSION'::character varying"))
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'USDT'::character varying"))

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.alter_column('completed_stages',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
        batch_op.alter_column('pro_notification_seen',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.create_foreign_key(None, 'partnertransaction', ['last_transaction_id'], ['id'])

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_partnertask_completed_at'), ['completed_at'], unique=False)

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_crypto', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_partnertransaction_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_index(batch_op.f('ix_xptransaction_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xptransaction_created_at'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partnertransaction_created_at'))
        batch_op.drop_column('amount_crypto')

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partnertask_completed_at'))
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('pro_notification_seen',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('completed_stages',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'USDT'::character varying"))
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'COMMISSION'::character varying"))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('balance_before', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('balance_after', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('related_partner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('event_category', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metadata', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('audit_log_partner_id_fkey'), 'partner', ['partner_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))
        batch_op.create_index(batch_op.f('ix_audit_log_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_related_partner_id'), ['related_partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_partner_id'), ['partner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_category_success'), ['event_category', 'success', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_admin_id'), ['admin_id'], unique=False)
        batch_op.drop_column('details')
        batch_op.drop_column('actor_id')
        batch_op.drop_column('action')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')

    op.create_table('blogpostengagement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('base_likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_likes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('blogpostengagement_pkey'))
    )
    with op.batch_alter_table('blogpostengagement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blogpostengagement_post_slug'), ['post_slug'], unique=True)

    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('network', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tx_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('transaction_partner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transaction_pkey'))
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_tx_hash'), ['tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_partner_id'), ['partner_id'], unique=False)

    op.create_table('partnerbloglike',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partner.id'], name=op.f('partnerbloglike_partner_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('partnerbloglike_pkey'))
    )
    with op.batch_alter_table('partnerbloglike', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partnerbloglike_post_slug'), ['post_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnerbloglike_partner_id'), ['partner_id'], unique=False)

    # ### end Alembic commands ###
