"""Add notifications_paused

Revision ID: e413c716e037
Revises: 881f1d2f1be3
Create Date: 2026-02-20 14:11:16.822425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e413c716e037'
down_revision: Union[str, Sequence[str], None] = '881f1d2f1be3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_earning_reference_id'))
        batch_op.create_index('idx_earning_partner_created', ['partner_id', 'created_at'], unique=False)
        batch_op.create_index('idx_earning_partner_type_created', ['partner_id', 'type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_earning_reference_id'), ['reference_id'], unique=False)
        batch_op.create_unique_constraint('uq_earning_reference_id', ['reference_id'])

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_paused', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index('idx_partner_ispro_expires', ['is_pro', 'pro_expires_at'], unique=False, postgresql_where=sa.text('is_pro = true'))
        batch_op.create_index('idx_partner_referrer_created', ['referrer_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_notifications_paused'), ['notifications_paused'], unique=False)
        batch_op.drop_column('completed_tasks')

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_partner_task', ['partner_id', 'task_id'])

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.create_index('idx_tx_partner_status_created', ['partner_id', 'status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnertransaction_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_partnertransaction_status'), ['status'], unique=False)

    with op.batch_alter_table('socialpost', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_socialpost_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_socialpost_generation_id'), ['generation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_socialpost_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('viralgeneration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viralgeneration_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_viralgeneration_partner_id'), ['partner_id'], unique=False)

    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.create_index('idx_xp_partner_created', ['partner_id', 'created_at'], unique=False)
        batch_op.create_unique_constraint('uq_partner_xp_ref', ['partner_id', 'type', 'reference_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_xp_ref', type_='unique')
        batch_op.drop_index('idx_xp_partner_created')

    with op.batch_alter_table('viralgeneration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viralgeneration_partner_id'))
        batch_op.drop_index(batch_op.f('ix_viralgeneration_created_at'))

    with op.batch_alter_table('socialpost', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_socialpost_partner_id'))
        batch_op.drop_index(batch_op.f('ix_socialpost_generation_id'))
        batch_op.drop_index(batch_op.f('ix_socialpost_created_at'))

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partnertransaction_status'))
        batch_op.drop_index(batch_op.f('ix_partnertransaction_currency'))
        batch_op.drop_index('idx_tx_partner_status_created')

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_task', type_='unique')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_tasks', sa.VARCHAR(), server_default=sa.text("'[]'::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_partner_notifications_paused'))
        batch_op.drop_index('idx_partner_referrer_created')
        batch_op.drop_index('idx_partner_ispro_expires', postgresql_where=sa.text('is_pro = true'))
        batch_op.drop_column('notifications_paused')

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_constraint('uq_earning_reference_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_earning_reference_id'))
        batch_op.drop_index(batch_op.f('ix_earning_level'))
        batch_op.drop_index(batch_op.f('ix_earning_currency'))
        batch_op.drop_index('idx_earning_partner_type_created')
        batch_op.drop_index('idx_earning_partner_created')
        batch_op.create_index(batch_op.f('idx_earning_reference_id'), ['reference_id'], unique=False)

    # ### end Alembic commands ###
