"""Empty migration

Revision ID: ee26570e6422
Revises: 
Create Date: 2026-02-07 00:51:43.841087

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ee26570e6422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('balance', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('level', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_partner_telegram_id'), 'partner', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partner_telegram_id'), table_name='partner')
    op.drop_table('partner')
    # ### end Alembic commands ###
