"""add_performance_indexes

Revision ID: fef308b386d4
Revises: 42aa9d7756cd
Create Date: 2026-02-20 14:37:15.566811

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fef308b386d4'
down_revision: str | Sequence[str] | None = '42aa9d7756cd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earning', schema=None) as batch_op:
        pass # Skipped unique constraint due to existing data overlaps

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.create_index('idx_partner_level_xp', ['level', 'xp'], unique=False)
        batch_op.create_index('idx_partner_pro_notif', ['is_pro', 'notifications_paused'], unique=False)

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        pass # Skipped unique constraint due to existing data overlaps

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.create_index('idx_tx_active_session', ['partner_id', 'currency', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        pass # Skipped unique constraint due to existing data overlaps

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xptransaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_xp_ref', type_='unique')

    with op.batch_alter_table('partnertransaction', schema=None) as batch_op:
        batch_op.drop_index('idx_tx_active_session')

    with op.batch_alter_table('partnertask', schema=None) as batch_op:
        batch_op.drop_constraint('uq_partner_task', type_='unique')

    with op.batch_alter_table('partner', schema=None) as batch_op:
        batch_op.drop_index('idx_partner_pro_notif')
        batch_op.drop_index('idx_partner_level_xp')

    with op.batch_alter_table('earning', schema=None) as batch_op:
        batch_op.drop_constraint('uq_earning_reference_id', type_='unique')

    # ### end Alembic commands ###
